name: Protocol Buffers CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'libs/proto-definitions/**'
      - '.github/workflows/proto-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'libs/proto-definitions/**'
      - '.github/workflows/proto-ci.yml'

jobs:
  proto-validation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install buf
      run: |
        curl -sSL \
          "https://github.com/bufbuild/buf/releases/download/v1.28.1/buf-$(uname -s)-$(uname -m)" \
          -o "/usr/local/bin/buf" && \
        chmod +x "/usr/local/bin/buf"
        
    - name: Install dependencies
      run: |
        npm ci
        go mod download
        
    - name: Lint proto files
      run: |
        cd libs/proto-definitions
        buf lint
        
    - name: Check for breaking changes
      run: |
        cd libs/proto-definitions
        buf breaking --against '.git#branch=main'
        
    - name: Generate proto files
      run: |
        cd libs/proto-definitions
        buf generate
        
    - name: Check generated files are up to date
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "Generated files are not up to date. Please run 'buf generate' and commit the changes."
          git status
          exit 1
        fi
        
    - name: Build Go services
      run: |
        cd apps/ticket-service
        go build -v ./...
        
    - name: Build TypeScript services
      run: |
        npm run build 